CREATE TABLE MyExpenses(category varchar(15), price NUMBER(10, 2));
insert into MyExpenses values ('Groceries', 60.23);
insert into MyExpenses values ('Groceries', 34.83);
insert into MyExpenses values ('Groceries', 94.32);
insert into MyExpenses values ('Groceries', 29.12);
insert into MyExpenses values ('Entertainment', 15.23);
insert into MyExpenses values ('Entertainment', 23.34);
insert into MyExpenses values ('Entertainment', 44.44);
insert into MyExpenses values ('Entertainment', 10.15);
insert into MyExpenses values ('Gas', 30.23);
insert into MyExpenses values ('Gas', 27.34);
insert into MyExpenses values ('Gas', 35.44);
insert into MyExpenses values ('Gas', 40.15);